# Generated by Django 4.1.5 on 2023-03-01 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('make', models.CharField(choices=[('BATA', 'Bata'), ('ADIDAS', 'Adidas'), ('PUMA', 'Puma'), ('REEBOK', 'Reebok'), ('NIKE', 'Nike'), ('WOODLAND', 'Woodland'), ('RED_CHIEF', 'Red Chief'), ('LEE_COOPER', 'Lee Cooper'), ('FILA', 'Fila'), ('SKECHERS', 'Skechers'), ('CONVERSE', 'Converse'), ('CLARKS', 'Clarks'), ('CROCS', 'Crocs'), ('HUSH_PUPPIES', 'Hush Puppies'), ('LIBERTY', 'Liberty'), ('SPARX', 'Sparx'), ('ACTION', 'Action'), ('LANCER', 'Lancer'), ('LOTTO', 'Lotto'), ('MOCHI', 'Mochi')], max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
