# Generated by Django 4.1.5 on 2023-01-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='my_num',
            field=models.IntegerField(default=0),
        ),
    ]
